--PayRoll_Bankruptcy (USA)
SELECT 
hr_empmstr.id as 'R-EmployeeID'
,'Steve Smigiel' as 'O-SourceSystem'
--hr_empmstr.entity_id = ROOT only as 'O-SourceSystem'
,BANKRUPTCY as 'R-WithholdingOrderTypeID'
,pyd_cdh_dtl.pyd_misc_l as 'R-CaseNumber'
,pyd_cdh_dtl.py_cdh_no  as 'O-WithholdingOrderAdditionalOrderNumber'
,pyd_cdh_dtl.pyd_beg as 'R-OrderDate'
,pyd_cdh_dtl.pyd_beg as 'R-ReceivedDate'
,pyd_cdh_dtl.pyd_beg as 'R-BeginDate'
,'' as 'O-EndDate'
,County of Macomb as 'R-Company'
,'' as 'O-Inactive'
,AMT as 'R-WithholdingOrderAmountType'
,pyd_cdh_dtl.pyd_amt as 'O-WithholdingOrderAmount'
,'' as 'O-WithholdingOrderAmountasPercent'
,if entity = ROOT then Biweekly if PENS then Monthly as 'R-FrequencyID'
,'' as 'O-TotalDebtAmountRemaining'
,'' as 'O-MonthlyLimit'
,FEDERAL as 'R-Code(IssuedinReference)'
,DR-001 as 'R-DeductionRecipientID'
,'' as 'O-OriginatingAuthority'
,'' as 'O-Memo'
,'' as 'O-Currency'
,'' as 'O-Chapter13'
,'' as 'O-Chapter7'
,0 as 'R-FeeAmount#1'
,'' as 'R-FeePercent#1'
,EMPLFEE_PER as 'R-FeeTypeID#1'
,AMOUNT as 'R-FeeAmountTypeID#1'
,'' as 'O-DeductionRecipientID#1'
,'' as 'O-OverrideFeeSchedule#1'
,'' as 'O-BeginDate#1'
,'' as 'O-EndDate#1'
,0 as 'R-FeeMonthlyLimit#1'
,0 as 'R-FeeAmount#2'
,0 as 'R-FeePercent#2'
,'' as 'R-FeeTypeID#2'
,AMOUNT as 'R-FeeAmountTypeID#2'
,'' as 'O-DeductionRecipientID#2'
,'' as 'O-OverrideFeeSchedule#2'
,'' as 'O-BeginDate#2'
,'' as 'O-EndDate#2'
,0 as 'R-FeeMonthlyLimit#2'
,'Bi-weekly' as 'O-WithholdingOrderWithholdingFrequency'
