--PayRoll_Deduction Recipients
SELECT
,County of Macomb, Michigan as 'R-DeductionRecipientName'
,'' as 'O-SourceSystem'
,'' as 'O-AlternateDeductionRecipientName'
,DR-001 as 'R-DeductionRecipientID'
,Check as 'R-PaymentType'
,County of Macomb, Michigan as 'R-BusinessEntityName'
,'' as 'O-BusinessEntityTaxID'
,DR-001 as 'R-ExternalEntityID'
,'' as 'O-EmailAddress'
,USA as 'R-CountryISOCodePhone'
,'' as 'O-InternationalPhoneCode'
,'' as 'R-PhoneNumber'
,'' as 'O-PhoneExtension'
,'' as 'R-PhoneDeviceType'
,Business as 'R-TypeReference'
,'' as 'O-UseForReferencePhone'
,USA as 'R-CountryISOCodeAddress'
,'' as 'O-Effectiveasof'
,120 N Main, 2nd Floor as 'O-AddressLine#1'
,'' as 'O-AddressLine#2'
,Mount Clemens as 'O-City'
,'' as 'O-CitySubdivision'
,'' as 'O-CitySubdivision2'
,USA-MI as 'O-Region'
,'' as 'O-RegionSubdivision'
,'' as 'O-RegionSubdivision2'
,48043 as 'O-PostalCode'
,'' as 'O-UseForReferenceAddress'
,'' as 'R-CountryISOCodeBank'
,USD as 'R-CurrencyCode'
,'' as 'O-BankAccountNickname'
,blank as 'R-BankName'
,blank as 'R-BankAccountTypeCode'
,blank as 'O-RoutingNumber(BankID)'
,'' as 'O-BranchID'
,'' as 'O-BranchName'
,blank as 'R-BankAccountNumber'
,'' as 'O-BankAccountName'
,'' as 'O-RollNumber'
,'' as 'O-CheckDigit'
,'' as 'O-IBAN'
,'' as 'O-SWIFTBankIdentificationCode'
