/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
no
,count(*)
/*TOP (1000) [ACTION_CD]
      ,[ADDAMT]
      ,[ADDBEG]
      ,[ADDEND]
      ,[ADDL_1]
      ,[ADDL_2]
      ,[ADDL_3]
      ,[ADDL_4]
      ,[AMT]
      ,[APPRV_CD01]
      ,[APPRV_CD02]
      ,[APPRV_CD03]
      ,[AXP]
      ,[BEG]
      ,[CD01]
      ,[CD02]
      ,[CD03]
      ,[CD04]
      ,[CDH_CODE]
      ,[CREATE_ERRORS]
      ,[CREATE_TIME]
      ,[CREATE_WHEN]
      ,[CREATE_WHO]
      ,[ENDDT]
      ,[ENTITY_ID]
      ,[FQ]
      ,[FQTYPE]
      ,[ID]
      ,[LMT]
      ,[LXP]
      ,[NO]
      ,[NOTES]
      ,[PLACEHOLDR]
      ,[RECORDFROM]
      ,[ST]
      ,[TRACK_CODE]
      ,[UPDATE_WHEN]
      ,[UPDATE_WHO]
      ,[VENDOR_CD]
      ,[UNIQUE_KEY]
      ,[LOCK_FLAG]
      ,[ADDRTYPE]
      ,[unique_id]
      ,[repbeg]
      ,[repend]*/
  FROM [production_finance].[dbo].[hr_cdhassgn]
  --where no in ('2980','2319','2349')
  group by no
  order by no